//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnomaliaItem
    {
        public int Id { get; set; }
        public int AnomaliaId { get; set; }
        public int TipoId { get; set; }
        public int StatusId { get; set; }
        public int NotaFiscalItemId { get; set; }
        public decimal QtdRecebida { get; set; }
        public decimal QtdReclamada { get; set; }
        public bool Instalado { get; set; }
        public int StatusEmbalagemId { get; set; }
        public string Observacoes { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
