//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFuncao
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string DescPTBR { get; set; }
        public string DescES { get; set; }
        public string CodComponente { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
