//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLogErro
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Instrucao { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
        public string Usuario { get; set; }
        public System.DateTime DataHora { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
