//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMenu
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Css { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Sequencia { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> IdNivelSup { get; set; }
        public bool HasChild { get; set; }
        public Nullable<System.DateTime> DatUltAtlz { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
