//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaRomaneio
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public Nullable<int> Prioridade { get; set; }
        public Nullable<bool> Separar { get; set; }
        public Nullable<bool> Conferir { get; set; }
        public Nullable<bool> Alocar { get; set; }
        public Nullable<bool> Mapa { get; set; }
    }
}
