//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CNPJ { get; set; }
        public string CodigoDMS { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> TipoId { get; set; }
        public Nullable<int> VendedorId { get; set; }
        public Nullable<int> RotaId { get; set; }
        public Nullable<int> ParadaId { get; set; }
        public string Endereco_Logradouro { get; set; }
        public string Endereco_Numero { get; set; }
        public string Endereco_Complemento { get; set; }
        public string Endereco_Bairro { get; set; }
        public string Endereco_Cidade { get; set; }
        public string Endereco_UF { get; set; }
        public string Endereco_CEP { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Telefone3 { get; set; }
        public string Observacoes { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
        public Nullable<int> TransportadoraId { get; set; }
        public Nullable<bool> Etiqueta { get; set; }
    }
}
