//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocExpedicao
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public string Classificacao { get; set; }
        public string Controle { get; set; }
        public string Vendedor { get; set; }
        public string CodigoCliente { get; set; }
        public string NomeCliente { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<bool> RoteiroImpresso { get; set; }
        public Nullable<int> RoteiroId { get; set; }
        public Nullable<int> TransportadoraId { get; set; }
        public Nullable<int> QtdVolumes { get; set; }
        public Nullable<int> RotaId { get; set; }
        public Nullable<int> ParadaId { get; set; }
        public string Movimento { get; set; }
        public Nullable<int> TipoMovimentoId { get; set; }
        public string Danfe { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Observacoes { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
