//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstoqueUpload_SERCON
    {
        public int Id { get; set; }
        public string Local { get; set; }
        public string Produto { get; set; }
        public string Descricao { get; set; }
        public string UN { get; set; }
        public Nullable<int> EmbalagemMin { get; set; }
        public Nullable<decimal> MediaVendas { get; set; }
        public Nullable<int> PedidoPendente { get; set; }
        public Nullable<decimal> CustoUnitario { get; set; }
        public Nullable<int> EstoqueIndisponivel { get; set; }
        public Nullable<int> EstoqueFisico { get; set; }
        public Nullable<decimal> ValorEstoque { get; set; }
        public System.DateTime Dtatual { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
