//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoArmazenagem
    {
        public long Id { get; set; }
        public string ItemNr { get; set; }
        public string Descricao { get; set; }
        public string Locacao { get; set; }
        public string LocacaoConfirmada { get; set; }
        public decimal Quantidade { get; set; }
        public System.DateTime DataHora { get; set; }
        public bool Erro { get; set; }
        public string Mensagem { get; set; }
        public string Usuario { get; set; }
        public int FilialId { get; set; }
    }
}
