//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoRecebimento
    {
        public long Id { get; set; }
        public string CodMaterial { get; set; }
        public string DescMaterial { get; set; }
        public string Curva { get; set; }
        public string CodLocacao { get; set; }
        public string NroVolume { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public System.DateTime DataHora { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
