//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locacao
    {
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public string Descricao { get; set; }
        public bool Bloqueado { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> EquipamentoId { get; set; }
        public string Curva { get; set; }
        public string Estrategia { get; set; }
        public string Observacoes { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public int Id { get; set; }
    
        public virtual Zona Zona { get; set; }
    }
}
