//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogZplGeneratedExpedicao
    {
        public int Id { get; set; }
        public string ZPL { get; set; }
        public Nullable<System.DateTime> GeradoEm { get; set; }
        public string Usuario { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
