//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public string UN { get; set; }
        public Nullable<int> EmbalagemMin { get; set; }
        public Nullable<decimal> MediaVendas { get; set; }
        public Nullable<decimal> CustoUnitario { get; set; }
        public string Curva { get; set; }
        public bool ItemCritico { get; set; }
        public string ObsItemCritico { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
        public string CategoriaProduto { get; set; }
        public string ItemApollo { get; set; }
        public Nullable<int> Zona1Id { get; set; }
        public Nullable<int> Eqpto1Id { get; set; }
        public Nullable<int> QtdePadrao1 { get; set; }
        public Nullable<int> Zona2Id { get; set; }
        public Nullable<int> Eqpto2Id { get; set; }
        public Nullable<int> QtdePadrao2 { get; set; }
        public Nullable<int> Zona3Id { get; set; }
        public Nullable<int> Eqpto3Id { get; set; }
        public Nullable<int> QtdePadrao3 { get; set; }
        public Nullable<decimal> Comp { get; set; }
        public Nullable<decimal> Larg { get; set; }
        public Nullable<decimal> Altu { get; set; }
    }
}
