//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Quasar_Entities : DbContext
    {
        public Quasar_Entities()
            : base("name=Quasar_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anomalia> Anomalia { get; set; }
        public virtual DbSet<AnomaliaItem> AnomaliaItem { get; set; }
        public virtual DbSet<AppComponente> AppComponente { get; set; }
        public virtual DbSet<AppFuncao> AppFuncao { get; set; }
        public virtual DbSet<AppLogErro> AppLogErro { get; set; }
        public virtual DbSet<AppMenu> AppMenu { get; set; }
        public virtual DbSet<AppSQL> AppSQL { get; set; }
        public virtual DbSet<DocExpedicao> DocExpedicao { get; set; }
        public virtual DbSet<Equipamento> Equipamento { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Estoque> Estoque { get; set; }
        public virtual DbSet<Etiqueta> Etiqueta { get; set; }
        public virtual DbSet<Fornecedor> Fornecedor { get; set; }
        public virtual DbSet<HistoricoArmazenagem> HistoricoArmazenagem { get; set; }
        public virtual DbSet<HistoricoDocExpedicao> HistoricoDocExpedicao { get; set; }
        public virtual DbSet<HistoricoRecebimento> HistoricoRecebimento { get; set; }
        public virtual DbSet<Impressora> Impressora { get; set; }
        public virtual DbSet<LogImpressao> LogImpressao { get; set; }
        public virtual DbSet<LogImpressaoExpedicao> LogImpressaoExpedicao { get; set; }
        public virtual DbSet<LogZplGeneratedExpedicao> LogZplGeneratedExpedicao { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<NotaFiscal> NotaFiscal { get; set; }
        public virtual DbSet<NotaFiscalItem> NotaFiscalItem { get; set; }
        public virtual DbSet<OrigemNotaFiscal> OrigemNotaFiscal { get; set; }
        public virtual DbSet<Parada> Parada { get; set; }
        public virtual DbSet<PerfilFuncao> PerfilFuncao { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<Rota> Rota { get; set; }
        public virtual DbSet<Roteiro> Roteiro { get; set; }
        public virtual DbSet<StatusAnomalia> StatusAnomalia { get; set; }
        public virtual DbSet<StatusCliente> StatusCliente { get; set; }
        public virtual DbSet<StatusDocExpedicao> StatusDocExpedicao { get; set; }
        public virtual DbSet<StatusEmbalagem> StatusEmbalagem { get; set; }
        public virtual DbSet<StatusEmpresa> StatusEmpresa { get; set; }
        public virtual DbSet<StatusFornecedor> StatusFornecedor { get; set; }
        public virtual DbSet<StatusNotaFiscal> StatusNotaFiscal { get; set; }
        public virtual DbSet<StatusRota> StatusRota { get; set; }
        public virtual DbSet<StatusTransportadora> StatusTransportadora { get; set; }
        public virtual DbSet<StatusVolume> StatusVolume { get; set; }
        public virtual DbSet<TipoAnomalia> TipoAnomalia { get; set; }
        public virtual DbSet<TipoDefeito> TipoDefeito { get; set; }
        public virtual DbSet<TipoEmpresa> TipoEmpresa { get; set; }
        public virtual DbSet<TipoHistoricoExpedicao> TipoHistoricoExpedicao { get; set; }
        public virtual DbSet<TipoMovimentoExpedicao> TipoMovimentoExpedicao { get; set; }
        public virtual DbSet<TipoNotaFiscal> TipoNotaFiscal { get; set; }
        public virtual DbSet<TipoRota> TipoRota { get; set; }
        public virtual DbSet<TipoTransportadora> TipoTransportadora { get; set; }
        public virtual DbSet<TipoVolume> TipoVolume { get; set; }
        public virtual DbSet<TransitoUploadColumns> TransitoUploadColumns { get; set; }
        public virtual DbSet<Transportadora> Transportadora { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
        public virtual DbSet<Volume> Volume { get; set; }
        public virtual DbSet<EstoqueUpload_SERCON> EstoqueUpload_SERCON { get; set; }
        public virtual DbSet<LocalDestino> LocalDestino { get; set; }
        public virtual DbSet<LocalOrigem> LocalOrigem { get; set; }
        public virtual DbSet<StatusRomaneio> StatusRomaneio { get; set; }
        public virtual DbSet<StatusRetorno> StatusRetorno { get; set; }
        public virtual DbSet<TipoDocumentoRetorno> TipoDocumentoRetorno { get; set; }
        public virtual DbSet<RetornoInterno> RetornoInterno { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Romaneio> Romaneio { get; set; }
        public virtual DbSet<AppConfig> AppConfig { get; set; }
        public virtual DbSet<PerfilAreaAcesso> PerfilAreaAcesso { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Movimentacao> Movimentacao { get; set; }
        public virtual DbSet<MovimentacaoDestino> MovimentacaoDestino { get; set; }
        public virtual DbSet<RetornoInternoItem> RetornoInternoItem { get; set; }
        public virtual DbSet<NotaFiscalTransportadora> NotaFiscalTransportadora { get; set; }
        public virtual DbSet<MotivoDevolucao> MotivoDevolucao { get; set; }
        public virtual DbSet<StatusDevolucao> StatusDevolucao { get; set; }
        public virtual DbSet<DevolucaoComplemento> DevolucaoComplemento { get; set; }
        public virtual DbSet<Locacao> Locacao { get; set; }
        public virtual DbSet<Ocorrencia> Ocorrencia { get; set; }
        public virtual DbSet<Devolucao> Devolucao { get; set; }
        public virtual DbSet<DevolucaoItem> DevolucaoItem { get; set; }
        public virtual DbSet<TipoArea> TipoArea { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<AreaPedido> AreaPedido { get; set; }
        public virtual DbSet<AreaRomaneio> AreaRomaneio { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<RomaneioItem> RomaneioItem { get; set; }
    
        public virtual ObjectResult<SP_GetLocacoesDisponiveis_Result> SP_GetLocacoesDisponiveis(string param)
        {
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetLocacoesDisponiveis_Result>("SP_GetLocacoesDisponiveis", paramParameter);
        }
    
        public virtual ObjectResult<SP_GetItensEstoque_Result> SP_GetItensEstoque()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetItensEstoque_Result>("SP_GetItensEstoque");
        }
    
        public virtual ObjectResult<SP_GetHistorico_Result> SP_GetHistorico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetHistorico_Result>("SP_GetHistorico");
        }
    }
}
