//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoDevolucao
    {
        public int Id { get; set; }
        public string Motivo { get; set; }
        public string FilialId { get; set; }
    }
}
