//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int Id { get; set; }
        public string ItemNr { get; set; }
        public string LocacaoOrigem { get; set; }
        public Nullable<int> QtdOrigem { get; set; }
        public string LocacaoDestino { get; set; }
        public Nullable<int> QtdDestino { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string FinalizadoPor { get; set; }
        public Nullable<System.DateTime> FinalizadoEm { get; set; }
        public string UrlDMS { get; set; }
        public string Payload { get; set; }
        public string Response { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
