//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaFiscal
    {
        public int Id { get; set; }
        public string Movimento { get; set; }
        public int TipoId { get; set; }
        public int StatusId { get; set; }
        public string Numero { get; set; }
        public string Serie { get; set; }
        public string Emissor { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Descricao { get; set; }
        public string Observacoes { get; set; }
        public string Danfe { get; set; }
        public Nullable<System.DateTime> RecebidoAdmEm { get; set; }
        public string RecebidoAdmPor { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
