//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaFiscalTransportadora
    {
        public int Id { get; set; }
        public string Transportadora { get; set; }
        public string NotaFiscal { get; set; }
        public Nullable<int> Volumes { get; set; }
        public string Cliente { get; set; }
        public string Contato { get; set; }
        public string VolumeNr { get; set; }
        public Nullable<int> FilialId { get; set; }
        public string Sequencia { get; set; }
        public string ZPL { get; set; }
    }
}
