//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetornoInterno
    {
        public int Id { get; set; }
        public string NrDocumento { get; set; }
        public int TipoDocumentoRetornoId { get; set; }
        public Nullable<int> LocalOrigemId { get; set; }
        public Nullable<int> LocalDestinoId { get; set; }
        public string Responsavel { get; set; }
        public string Observacoes { get; set; }
        public Nullable<System.DateTime> FinalizadoEm { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
