//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RomaneioItem
    {
        public int Id { get; set; }
        public int RomaneioId { get; set; }
        public string ItemNr { get; set; }
        public Nullable<int> Qtde { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
        public string TarefaNr { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> SeparadorId { get; set; }
        public Nullable<System.DateTime> DataSeparador { get; set; }
        public Nullable<int> ConferenteId { get; set; }
        public Nullable<System.DateTime> DataConferente { get; set; }
        public Nullable<int> LocacaoId { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> QtdeSeparada { get; set; }
        public Nullable<int> QtdeConferida { get; set; }
    }
}
