//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Romaneio
    {
        public int Id { get; set; }
        public string RomaneioNr { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<int> VendedorId { get; set; }
        public Nullable<int> Contato { get; set; }
        public Nullable<int> SeparadorId { get; set; }
        public Nullable<System.DateTime> DataSeparador { get; set; }
        public Nullable<int> ConferenteId { get; set; }
        public Nullable<System.DateTime> DataConferente { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Localizacao { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
