//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransitoUploadColumns
    {
        public int Id { get; set; }
        public string RecordType { get; set; }
        public string NotaFiscal { get; set; }
        public string Origem { get; set; }
        public string Emissao { get; set; }
        public string Volume { get; set; }
        public string Item { get; set; }
        public string Pedido { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public System.DateTime Dtatual { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
