//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volume
    {
        public string NotaFiscalNr { get; set; }
        public string VolumeNr { get; set; }
        public int StatusId { get; set; }
        public int AreaId { get; set; }
        public int QtdItens { get; set; }
        public bool Imprimir { get; set; }
        public string Danfe { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
    }
}
