//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplify.Quasar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zona()
        {
            this.Locacao = new HashSet<Locacao>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> ProntoDespacho { get; set; }
        public Nullable<int> QtdeArmazenagem { get; set; }
        public Nullable<int> QtdeLinha { get; set; }
        public Nullable<decimal> ValorPedido { get; set; }
        public Nullable<int> QtdeCliente { get; set; }
        public string CriadoPor { get; set; }
        public Nullable<System.DateTime> CriadoEm { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEm { get; set; }
        public Nullable<int> FilialId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locacao> Locacao { get; set; }
        public virtual Area Area { get; set; }
    }
}
