<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Routes\Operations\NewFolder\**" />
    <Content Remove="Routes\Operations\NewFolder\**" />
    <EmbeddedResource Remove="Routes\Operations\NewFolder\**" />
    <None Remove="Routes\Operations\NewFolder\**" />
    <Content Remove="artifacts\**;build-verify\**;publish\**" />
    <EmbeddedResource Remove="artifacts\**;build-verify\**;publish\**" />
    <None Remove="artifacts\**;build-verify\**;publish\**" />
    <Content Update="package.json;package-lock.json" CopyToPublishDirectory="Never" />
    <None Update="package.json;package-lock.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\Operations\Expedicao\" />
    <Folder Include="DTO\Operations\Inventario\" />
    <Folder Include="DTO\Operations\Recebimento\Descarga\" />
    <Folder Include="DTO\Operations\Separacao\" />
  </ItemGroup>

</Project>
